[package]
name = "tracer"
version = "0.1.0"
authors = ["peter <PeterRong96@gmail.com>", "Jianxiong Cai <caijx@shanghaitech.edu.cn>"]

[dependencies]
libc = "0.2.23"

[lib]
name = "tracer"
path = "src/lib.rs"